version: 2
jobs:
  build:
    docker:
      - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
        environment:
          AWS_REGION: us-west-2
          AMI_PREFIX: jibakurei
          AMI_NAME: amzn2-base

    steps:
      - checkout
      - run:
          name: Validate
          command: packer validate packer.json
      - run:
          name: Build
          command: aws dynamodb list-tables --region $AWS_REGION
