# defaults: &defaults
#   docker:
#     - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
#   environment:
#     - AWS_REGION: us-west-2
#     - AWS_PREFIX: jibakurei
#     - AMI_NAME: amzn2-base

# version: 2
# jobs:
#   packer_validate:
#     <<: *defaults
#     steps:
#       - checkout
#       - run:
#           name: Packer Validate
#           command: packer validate packer.json

#   packer_build:
#     <<: *defaults
#     steps:
#       - checkout
#       - run:
#           name: Packer Build
#           command: packer build packer.json


# workflows:
#   version: 2
#   commit:
#     jobs:
#       - packer_validate
#       - packer_build:
#           filters:
#             branches:
#               only:
#                 - master
#   nightly:
#     triggers:
#       - schedule:
#           cron: "0 0 * * *"
#           filters:
#             branches:
#               only:
#                 - master
#     jobs:
#       - packer_build


defaults: &defaults
  docker:
    - image: centos:latest
  working_directory: ~/app
  environment:
    - AWS_REGION: us-west-2
    - AWS_PREFIX: jibakurei
    - AMI_NAME: amzn2-base

version: 2
jobs:
  wf_first_job:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: 1st Job Run
          command: echo "Success" > firstJob.txt

  wf_second_job:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Packer Build
          command: ls -la /root/app

workflows:
  version: 2
  commit:
    jobs:
      - wf_first_job
      - wf_second_job:
          filters:
            branches:
              only:
                - master












