defaults: &defaults
  docker:
    - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
  working_directory: ~/app
  environment:
    - AWS_REGION: us-west-2
    - AWS_PREFIX: jibakurei
    - AMI_NAME: amzn2-base

version: 2
jobs:
  packer_validate:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Packer Validate
          command: packer validate packer.json
      - persist_to_workspace:
          root: packer-project
          paths:
            - .

  packer_build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/app/packer-project
      - run:
          name: Packer Build
          command: cd /root/app/packer-project && packer build packer.json

workflows:
  version: 2
  weekly:
    triggers:
    - schedule:
        cron: "* 5 * * *"
        filters:
          branches:
            only:
              - master
    jobs:
      - packer_validate
      - packer_build:
          requires:
            - packer_validate
