defaults: &defaults
  docker:
    - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
  working_directory: ~/app
  environment:
    - AWS_REGION: us-west-2
    - AMI_PREFIX: jibakurei
    - AMI_NAME: amzn2-base

version: 2
jobs:
  packer_validate:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Packer Validate
          command: packer validate packer.json

  packer_build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: ENVs
          command: env
      - run:
          name: Packer Build
          command: packer build packer.json

workflows:
  version: 2
  commit:
    jobs:
      - packer_validate
      - packer_build:
          requires:
            - packer_validate
          filters:
            branches:
              only:
                - master
